default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  Host: ec2-34-193-44-192.compute-1.amazonaws.com
Database: d7vrc25682qbdj
User: sxydyomeutypdv
Port: 5432
Password: 9fd3b2ca5dee3a228bd8a28c202db8dd922b190b74db2eec7abc3ada8ae00330 